### ISSUE TITLE
python speadsheet to _pet.json

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/PET2BIDS#103]
Add multi support for multiple spreadsheet input. Default spreadsheet ingestion to accept examples at [multiple subject](https://github.com/openneuropet/PET2BIDS/tree/main/spreadsheet_conversion/many_subjects_sheet) and [single subject](https://github.com/openneuropet/PET2BIDS/tree/main/spreadsheet_conversion/single_subject_sheet) examples.

**Comment by CPernet** [comment]
all the python code is gone from https://github.com/openneuropet/PET2BIDS/tree/main/spreadsheet_conversion -- last leg to do!

**Comment by CPernet** [comment]
still single subject case to do https://github.com/openneuropet/PET2BIDS/tree/main/spreadsheet_conversion/single_subject_sheet
