### ISSUE TITLE
default readme in BIDS dataset after conversion

### ISSUE THREAD

**Issue by Remi-Gau** [openneuropet/PET2BIDS#127]
hey

We (BIDS maintainers) are trying to see if we can improve the quality of the average README in BIDS dataset. Those tend to be pretty thin and are missing some information we would like to see there even if it can be formalized "yet" into the BIDS specification.

Hoping to leverage the bids converters to help to do.

So I am going around the different BIDS converters repo to see if we can start improving the  default README they put in a the BIDS dataset.

There is template that is provided in the BIDS starter kit: https://github.com/bids-standard/bids-starter-kit/blob/main/templates/README.MD

Some possible options:
1. use this template is
2. use a subset of it
3. add a link to the template README
4. something else (a mix of 2 and 3?)

What do you think? I can try to open a PR if you want.

Also let us know if you think that the template README in the starter kit could / should be improved .

Feel free to disregard if you are already using some version of the template README.

**Comment by CPernet** [comment]
pas compris ce que tu veux faire? m.a.j. les exemples PET?

**Comment by Remi-Gau** [comment]
nope 

ensure that PET2BIDS either:
- creates a template README to help the user know what they should put in there 
- or creates a README that point to an existing template 

So as to avoid README that are useless and just there to pacify the validator.

Example: https://openneuro.org/datasets/ds004228/versions/1.0.0

**Comment by CPernet** [comment]
oh the insult man, our readme is beautiful ... 
right ok we'll have a good look and update

**Comment by CPernet** [comment]
to do with @melanieganz who's now been tagged since she has been working on this already

**Comment by bendhouseart** [comment]
add this to https://github.com/bids-standard/bids-starter-kit/blob/0beb4c850616b5defa22b1c0a19a9337c332fd46/templates/README.MD

**Comment by CPernet** [comment]
I actually don't think it is relevant because PET2BIDS does not create datasets, and this no dataset_description.json and README. We convert files and that is it.

**Comment by CPernet** [comment]
1 - the name should be changed to PET2BIDS in the sheet
2 - the description is correct (Helps you convert your PET data! raw PET scanner files (for example ecat, dicom) and additional side file like excel sheets.)
3 - this differs markedly from tools that say 'Tool to convert source MRI datasets to BIDS-compatible datasets.' we do not claim to make datasets ; a converter convert files but some tools additionally make a file structure we don't

**Comment by Remi-Gau** [comment]
> 1 - the name should be changed to PET2BIDS in the sheet 

oops. will do

> 3 - this differs markedly from tools that say 'Tool to convert source MRI datasets to BIDS-compatible datasets.' we do not claim to make datasets ; a converter converts files but some tools additionally make a file structure we don't

yes that is what I meant: the sheet should make a distinction between the 2
