### ISSUE TITLE
Include Scanner File Text

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/PET2BIDS#13]
Need to include the scanner information contained in the text files `SiemensHRRTparameters.txt` into the python converter/reader.

**Comment by CPernet** [comment]
The [GEAdvanceparameters.txt](https://github.com/openneuropet/BIDS-converter/blob/main/code/GEAdvanceparameters.txt) and [SiemensHRRTparameters.txt](https://github.com/openneuropet/BIDS-converter/blob/main/code/SiemensHRRTparameters.txt) are at the code root folder - note those are templates, and are meant to live next to your code once filled (the matlab code generate those template if it cannot find them - unless all parameters are passed along as input)

**Comment by bendhouseart** [comment]
Why are the lines for the GE template wrapped in `" "` while the Siemens are not?

**Comment by CPernet** [comment]
I will merge the 3 get_XXX.m function into one, passing scanner as argument
