### ISSUE TITLE
Phantom Conversion Code

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/PET2BIDS#136]
Add sample code to convert phantom data set, dependent on full phantom set w/ blood and radiological data (can be fake). 

- [x] Create Fake Blood/Radio Data to accompany images missing such
- [x] Write python code that produces valid bids output from phantoms
- [x] Write matlab code taht produces valid bids output from phantoms
- [ ] #152
- [x] ~Update documentation to refer to Phantom/Test Data set~ <---waiting until phantoms can be freely published and/or CI is properly working. Lack of access to source files deprioritizes this in this developers eye.

**Comment by CPernet** [comment]
the matlab code is in the code directory in the open neuropet google drive
I need to update for Århus data and there GE (and the Amsterdam people, like your NIMH colleagues don't give me the phantom weight and injected mass = half useful code wiwe)
