### ISSUE TITLE
DICOM names and BIDS fields

### ISSUE THREAD

**Issue by neurolabusc** [openneuropet/PET2BIDS#193]
[dcm2niix issue 669](https://github.com/rordenlab/dcm2niix/issues/669) seems relevant here. dcm2niix included DICOM tags before the [BIDS PET BEP 009](https://bids.neuroimaging.io/get_involved.html#extending-the-bids-specification) was created. Following the historical BIDS convention, dcm2niix used the DICOM names for the JSON fields for a one-to-one mapping. However, BEP009 coined new terms for these fields:

```
tag	        name in current dcm2niix	name in latest BIDS spec
-------------------------------------------------------------------------
0018,0031	Radiopharmaceutical	        (disappeared?)
0018,1076	RadionuclidePositronFraction	(disappeared?)
0018,1075	RadionuclideHalfLife	        (disappeared?)
0018,1074	RadionuclideTotalDose	        InjectedRadioactivity
0018,1210	ConvolutionKernel	        ReconFilterType
0054,1101	AttenuationCorrectionMethod	AttenuationCorrection
0054,1102	DecayCorrection	                (disappeared?)
0054,1103	ReconstructionMethod	        ReconMethodName
0054,1321	DecayCorrectionFactor	        DecayFactor
0008,0022	FrameTimesStart	                ScanDate (?)
```
DICOM names

 - [Radionuclide Total Dose (0018,1074)](https://dicom.innolitics.com/ciods/nm-image/nm-isotope/00540016/00181074)
 - [Convolution Kernel (0018,1210)](https://dicom.innolitics.com/ciods/ct-image/ct-image/00181210)
 - [Attenuation Correction Method (0054,1101)](https://dicom.innolitics.com/ciods/pet-image/pet-series/00541101)
 - [Decay Correction (0054,1102)](https://dicom.innolitics.com/ciods/pet-image/pet-series/00541102)
 - [Reconstruction Method (0054,1103)](https://dicom.innolitics.com/ciods/pet-image/pet-series/00541103)
 - [Decay Correction Factor (0054,1321)](https://dicom.innolitics.com/ciods/pet-image/pet-image/00541321)

Seeing that PET2BIDS uses dcm2niix to create BIDS data, what changes should be done. There are several options. I do not have a strong preference, and am happy to implement the strategy you suggest.
 1. Leave dcm2niix unchanged: PET2BIDS will translate names to match BEP009.
 2. Leave dcm2niix unchanged: The BEP009 fields will be changed to use DICOM names when there is a one-to-one mapping.
 3. dcm2niix should use BEP009 names instead of DICOM names.
 4. dcm2niix should provide two entries for each of these fields: one being the DICOM name and the other being the BEP009 term.

**Comment by CPernet** [comment]
1. PET2BIDS will translate names --> PET2BIDS does translate names
We handle this via [dicom2bids.json](https://github.com/openneuropet/PET2BIDS/blob/main/metadata/dicom2bids.json) 
2. BEP009 very unlikely to change
3. possibly but some mapping is simply not unique
4. seems overkill

**Comment by neurolabusc** [comment]
OK, closing this issue. dcm2niix will remain unchanged. This issue is now resolved.
