### ISSUE TITLE
pypet2bids limits pytest verison 

### ISSUE THREAD

**Issue by dlevitas** [openneuropet/PET2BIDS#239]
Hi @bendhouseart,

I'm trying to package the most recent version of pytest (7.4.3) with the ezBIDS Dockerfile, but I'm seeing this error message:
`ERROR: pypet2bids 1.2.8 has requirement pytest<7.0.0,>=6.2.5, but you'll have pytest 7.4.3 which is incompatible.`

I'm happy to specify a compatible pyttest version in my Dockerfile, but I was wondering whether it's too much trouble to allow more recent pytest versions. Particularly given that the most recent compatible version would be `6.2.5`, released back in 2021.

Thanks

**Comment by bendhouseart** [comment]
@dlevitas bumped and closed, please re-open issue if it gives you trouble.

**Comment by dlevitas** [comment]
thanks @bendhouseart I tried again but am still seeing the error message.

I also tried `pip3 install pypet2bids` with `pytest` (v 7.4.3) already installed and it uninstalled my version and re-installed version 6.2.5

**Comment by dlevitas** [comment]
works now after pypl update
