### ISSUE TITLE
[JOSS] Suggestion: Consider adding instructions to run tests 

### ISSUE THREAD

**Issue by adswa** [openneuropet/PET2BIDS#247]
Hi! I've been exploring this software for the JOSS review of your paper. :) I see that there are automated tests (which fulfills the check mark criterion for the review checklist - so this is just a suggestion). I tried to run the tests (at least the Python tests), but couldn't get them to run with a brief time investment, and also couldn't find documentation which tests I may be able to run locally with what procedure. To make the lives of future contributors easier, you could consider adding testing instructions (e.g., which environment variables need to be set, which test data needs to be available, how to invoke tests) to the CONTRIBUTING file or the documentation.

**Comment by bendhouseart** [comment]
Yeah, unfortunately the actual integration tests rely on some data that we aren't _yet_ able to publish, so I've held off on documenting it as one wouldn't be able to run them.... I think though that I should do some refactoring and publish one of the "subjects" I am able to to github actions and gdrive such that on is able to do so. I just needed the push.
