### ISSUE TITLE
[JOSS] Suggestion: Streamline Python installation a bit more

### ISSUE THREAD

**Issue by adswa** [openneuropet/PET2BIDS#248]
This is again a suggestion, and again refers to the Python part of the software. 

There are dependency declarations and they are handled with automated package management solutions (check mark review checklist). 
However, I noticed that the different installation instructions for Python result in deferentially useful sets of packages: A from-source installation gets me development relevant packages like pytest in addition to dependencies relevant for standard usage, a poetry-based installation gives me the Sphinx-dependencies necessary to build the docs in addition.

I would argue that standard users wouldn't need to run tests or build docs, but those inclined to contribute would. It would be cool if installations for both of these groups (standard users: just those dependencies that are relevant for using the tool; contributors: dependencies for testing and documentation building) would be easily possible, documented, and consistent across installation methods.

**Comment by CPernet** [comment]
sounds like a cool feature! @bendhouseart can do that I'm sure

**Comment by bendhouseart** [comment]
Updating top level README.md and docs here -> https://github.com/openneuropet/PET2BIDS/pull/253

Preview of read the docs can be seen at the following link -> https://pet2bids--253.org.readthedocs.build/en/253/
