### ISSUE TITLE
Installation instruction: duplication in the docs

### ISSUE THREAD

**Issue by adswa** [openneuropet/PET2BIDS#249]
I noticed the the [documentation](https://pet2bids.readthedocs.io/en/latest/installation.html#) partially exposes the "additional installation notes" in the side bar toctree even though its part of the "installation" source files. If someone reads the docs sequentially, they will read those sections twice.
To avoid this, you could for example consider making the additional install notes a separate file, or to tweak the RST heading levels in ``installation.rst`` to not render "Additional Install Notes" as a top-level heading.

![image](https://github.com/openneuropet/PET2BIDS/assets/29738718/0e498d12-abc6-491a-b3d9-5f91913c643a)

**Comment by bendhouseart** [comment]
Fixed as of #257 

see https://pet2bids.readthedocs.io/en/latest/installation.html

or 

![Image](https://github.com/openneuropet/PET2BIDS/assets/28850131/b4470a6e-3b6c-4ab9-be85-60b106d53542)
