### ISSUE TITLE
BUG: ecatpet2bids.py: negative values overflowing into positive ones

### ISSUE THREAD

**Issue by nbeliy** [openneuropet/PET2BIDS#294]
**Describe the bug**
Having an ECAT7 image with negative voxels (we have images reconstructed with FBP), the converted images contains only positive and very large values. Where spm's `spm_ecat2nifti` shows -2266.532958984375, `ecatpet2bids` produces 72494.859375

Positive values are the same, comparing with spm.

**To Reproduce**
Convert ECAT image with negative values

**Expected behaviour**
The negative values must be conserved.

**Desktop (please complete the following information):**
Python 3.8.10
pypet2bids==1.3.9

**Comment by mnoergaard** [comment]
Hi @nbeliy. Thanks for raising this issue. We are of aware of this bug for the python part (https://github.com/openneuropet/PET2BIDS/issues/272), and are currently working on a solution. Matlab version works fine.

**Comment by nbeliy** [comment]
Ah, ok.

If it could help, problem may come from [read_ecat.py:408](https://github.com/openneuropet/PET2BIDS/blob/5eee4e8fac89ce8a33ad7540d2bbc0e3ffec192a/pypet2bids/pypet2bids/read_ecat.py#L408), where data type 6 is interpreted as unsigned int16 (`>H`), while [nibabel](https://github.com/nipy/nibabel/blob/a2e5dee05cf374c22670ff9fd0d385ce366eb495/nibabel/ecat.py#L201) interprets as signed int16.  SPM treats all data types as int16.

Nibabel reference some documents on Turku website, but the documents are no longer there.

As I'm here, the lines []():
```python
    if ".gz" in ecat_file:
        ecat_file = decompress(ecat_file)
```
may cause a crash if the name of file contains `.gz` somewhere in the middle. It will be better to replace the if by:
```python
    if ecat_file.endswith(".gz"):
        ecat_file = decompress(ecat_file)
```

**Comment by bendhouseart** [comment]
Duplicate issue to #272, closing.
