### ISSUE TITLE
Double check Title and Author list. in archive matches paper

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/PET2BIDS#299]

**Comment by melanieganz** [comment]
Ensure to add @bilgelm to the authors here (JOSS) and contributor list (repo)

**Comment by bendhouseart** [comment]
Murat was easy enough to include and the paper currently matches the contributor list, barring Cyrus not being listed in contributors.md?

See attached: 
[paper 3.pdf](https://github.com/openneuropet/PET2BIDS/files/15179150/paper.3.pdf)


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/galassiae/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/galassiae/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


Collaborators | Listed in Paper.md | Listed in Contributors.md | Listed on github page for pet2bids | github user name
-- | -- | -- | -- | --
Anthony Galassi | Yes | Yes | Yes | bendhouseart
Cyrus Eierud | Yes | No | No | DrCyPhi
Martin Norgaard | Yes | Yes | Yes | mnoergaard
Adam G. Thomas | Yes | Yes | Yes | agt24
Gabriel Gonzalez-Escamilla | Yes | Yes | Yes | GGonEsc
Claus Svarer | Yes | Yes | No |  
Chris Rorden | Yes | Yes | yes | neurolabusc
Granville J. Matheson | Yes | Yes | no |  
Gitte M. Knudsen | Yes | Yes | no |  
Robert B. Innis | Yes | Yes | no |  
Melanie Ganz | Yes | Yes | yes | melanieganz
Murat Bilgel | Yes | Yes | yes | bilgelm
Cyril Pernet | Yes | Yes | yes | Cpernet
  | no | no | yes | fishpm
  | no | no | yes | noah-neuroimage
marcel wiers | no | no | yes | marcelzwiers
Keith Jamison | no | no | yes | kjamison
Remi Gau | no | no | yes | Remi-Gau

</body>
</html>

Should I call this done @melanieganz ? Or do I need to track down and add the collaborators that aren't listed in contributors.md but do appear on as contributors on the repo page?

**Comment by bendhouseart** [comment]
Matches paper.md, contributors.cff, and orcid's work on links in generated paper here -> 
[paper 4.pdf](https://github.com/openneuropet/PET2BIDS/files/15191120/paper.4.pdf)
