### ISSUE TITLE
Standardize Radiochemistry Metadata (Case/Order)

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/PET2BIDS#319]
We're noticing that we get repeated values on our metadata for our pet datasets, much of this could be solved by changing the case to upper/lower for specific fields during the conversion process. See [this dataset on openneuro](https://openneuro.org/datasets/ds004869/versions/1.0.1) for an example.

Fix:

- [x] Order of isotope number should be 11C not C11, remove brackets [11C] etc etc 
- [x] Capitalize abbreviation for RadioTracer
- [x] lower case for ModeOfAdministration 
- [x] TBD

**Comment by CPernet** [comment]
- [ ] Order of isotope number should be 11C not C11, remove brackets [11C] etc etc --> I would say we update https://github.com/openneuropet/PET2BIDS/blob/main/metadata/PET_Radionuclide.mkd instead with a new column for the corresponding radioisotope name ensuring it is always the same and matches the dicom code value if present
- [ ] upper/lower/Capitalize --> what the BIDS rules if any, then we can take from there, there is a move to all lower if I am not mistaking

**Comment by bendhouseart** [comment]
> * upper/lower/Capitalize --> what the BIDS rules if any, then we can take from there, there is a move to all lower if I am not mistaking

I think it only goes so far as to specify string, but @mnoergaard and I were talking and for RadioTracer at least we wanted to align what users are doing in the field. One can always change upper to lower or vice versa after the fact with some bash magic, so until it's in the standard I agree with Martin in going with what the community at large practices.

**Comment by bendhouseart** [comment]
Not sure why this didn't get closed with PR #321, found a second branch #319 and am merging that in as well.
