### ISSUE TITLE
Add converter for excel to json for metadatain (python)

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/PET2BIDS#32]
Per Cyril's request: ~"create a small converter for json only from the excel template Martin made [here](https://github.com/openneuropet/BIDS-converter/tree/main/Metadata_in)"

**Comment by CPernet** [comment]
can we have this as a single function ~= matlab one and shared inside the https://github.com/openneuropet/PET2BIDS/tree/main/spreadsheet_conversion folder - thx

**Comment by bendhouseart** [comment]
Right now it's kind of broken up into two functions, such that first a spreadsheet is loaded as a pandas dataframe object and then that object is acted upon by an external script. The json manipulation bit is put into test, but I can copy it to the spreadsheet conversion folder no problem and rename it python sample. 

I think ultimately json input and manipulation scripts need to be made into their own repository as it seems like a sensible thing to break out from this monorepo. I'm considering making a separate bids/json metadata manipulation repo so that all of our python tools can more easily import those methods.

**Comment by bendhouseart** [comment]
Cyril, I think this is good to go, but I really need to cache the installation of opengl, etc etc on ubuntu to speed up the CI now that I've added a GUI into the mix. This issue and PR should be closed after all the CI checks pass.

**Comment by bendhouseart** [comment]
Closed with pull request #50
