### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by RDoerfel** [openneuropet/PET2BIDS#327]
**Describe the bug**
When installing in a naive environment, I get the error "ModuleNotFoundError: No module named 'requests'" when running `dcm2niix4pet` in the terminal.

**Expected behaviour**
I would expect to be able to run the command.

**Desktop (please complete the following information):**
 - Windows 10. python=3.10

After adding `requests` to the environment, everything was fine. I would suggest adding this to the `pyproject.toml`.

**Comment by bendhouseart** [comment]
Thanks for the catch @RDoerfel is fixed in the attached branch.

**Comment by bendhouseart** [comment]
@RDoerfel closed and published to PyPi as `pypet2bids==1.3.16`

Happy Holidays!
