### ISSUE TITLE
Blood data for Pmod

### ISSUE THREAD

**Issue by murgysc** [openneuropet/PET2BIDS#49]
convert between "bld" (Pmod specific bloosd data) and "tsv" data. 
- Pmod data are already tab-separated. 
- Time is in minutes
- Whole blood activity data can contain merged manual and automatic samples

**Comment by CPernet** [comment]
can you share those pmod files you showed me? (adding some random noise so for sure this is not patient data at all) - I'll make the merger and you can test it

**Comment by CPernet** [comment]
https://doc.pmod.com/pkin/importofblooddata6839.html

**Comment by CPernet** [comment]
this  seems to work now, thx
