### ISSUE TITLE
generated ecat file with known value for unit test

### ISSUE THREAD

**Issue by CPernet** [openneuropet/PET2BIDS#55]
see also https://github.com/openneuropet/PET2BIDS/issues/35

**Comment by CPernet** [comment]
the new synthetic data have an issue with reading the number of frames -- the matlab ecatread, returns this info from reading the bytes

mh = readMainheader(fid)

mh = 

  struct with fields:

                magic_number: 'MATRIX73v     '
          original_file_name: 'GoldenECATInteger               '
                  sw_version: 73
                 system_type: 328
                   file_type: 7
               serial_number: 'HRRT      '
             scan_start_time: 1.5566e+09
                isotope_name: 'C-11    '
            isotope_halflife: 1224
         radiopharmaceutical: 'unknown                         '
                 gantry_tilt: 0
             gantry_rotation: 0
               bed_elevation: 0
              intrinsic_tilt: 0
                wobble_speed: 0
          transm_source_type: 3
            distance_scanned: 25.2281
              transaxial_fov: 31.2000
         angular_compression: 3
              coin_samp_mode: 2
             axial_samp_mode: 0
     ecat_calibration_factor: 64518900
           calibration_units: 1
     calibration_units_label: 1
            compression_code: 0
                   stud_type: 'Golden      '
                  patient_id: 'PerfectPatient  '
                patient_name: 'Majesty                         '
                 patient_sex: 'U'
           patient_dexterity: 'U'
                 patient_age: 0
              patient_height: 0
              patient_weight: 0
          patient_birth_date: -1
              physician_name: '                                '
               operator_name: '                                '
           study_description: '                                '
            acquisition_type: 4
         patient_orientation: 8
               facility_name: 'Virtual             '
                  num_planes: 207
                  num_frames: 16
                   num_gates: 1
                 num_bed_pos: 0
           init_bed_position: 0
                bed_position: [15×1 double]
            plane_separation: 0.1219
              lwr_sctr_thres: 0
              lwr_true_thres: 400
              upr_true_thres: 650
           user_process_code: '          '
            acquisition_mode: 0
                    bin_size: 0.1219
          branching_fraction: 0.9976
             dose_start_time: 1.5566e+09
                      dosage: 2.1000
    well_counter_corr_factor: 0
                  data_units: 'Bq/ml                           '
                 septa_state: 1
                        fill: [6×1 double]

coming from reading the 1st column of the binary as
mh.num_planes                 = fread(fid,1,'int16');
mh.num_frames                 = fread(fid,1,'int16');

**Comment by bendhouseart** [comment]
Wasn't updating the header appropriately during creation. Is fixed in main now see -> https://github.com/openneuropet/PET2BIDS/blob/cacd9b40357dc33fbc39430ba92d7cd438e476b1/pypet2bids/pypet2bids/golden_ecat.py#L79
