### ISSUE TITLE
acquisition time vs time zero

### ISSUE THREAD

**Issue by CPernet** [openneuropet/PET2BIDS#69]
@bendhouseart check that update https://github.com/openneuropet/PET2BIDS/commit/f5c86ac633b53eefb42b63eeb62d4c7c2d6f49d6
in the python code, do check that time info matches the spec (also dcm2niix acquisition time should be renamed but depends on what the user tells what is TimeZero)

**Comment by bendhouseart** [comment]
@bendhouseart Tagging myself for a reminder.
