### ISSUE TITLE
Write a Paper for the Journal of Open Science Software

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/PET2BIDS#71]
This seems pretty straight forward see: https://joss.theoj.org/

And documenation here: https://joss.readthedocs.io/en/latest/submitting.html

**Comment by CPernet** [comment]
started it as a branch https://github.com/openneuropet/PET2BIDS/tree/JOSS_paper

**Comment by CPernet** [comment]
it's written now and the action run --> https://github.com/openneuropet/PET2BIDS/actions/runs/5936971364/job/16098466945
but aren't we supposed to see the pdf somewhere??

**Comment by CPernet** [comment]
note I have also updated https://github.com/openneuropet/PET2BIDS/blob/main/paper/persons_info.txt (along with https://github.com/openneuropet/PET2BIDS/blob/main/contributors.md and https://github.com/openneuropet/PET2BIDS/blob/main/CITATION.cff) -- ie can you rebuild https://github.com/openneuropet/PET2BIDS/blob/main/paper/codemeta.json

also note sure where codemeta.json should seat? in paper? or just root (seems more logical -- can't find the JOSS link about that)

**Comment by bendhouseart** [comment]
> it's written now and the action run --> https://github.com/openneuropet/PET2BIDS/actions/runs/5936971364/job/16098466945 but aren't we supposed to see the pdf somewhere??

Well, this isn't super clear:

```
Run actions/upload-artifact@v1
Uploading artifact 'paper' from '/home/runner/work/PET2BIDS/PET2BIDS/paper.pdf' for run #224[5](https://github.com/openneuropet/PET2BIDS/actions/runs/5936971364/job/16098466945#step:5:6)
Uploading 1 files
File upload complete.
Uploaded '20[6](https://github.com/openneuropet/PET2BIDS/actions/runs/5936971364/job/16098466945#step:5:7)252' bytes from '/home/runner/work/PET2BIDS/PET2BIDS/paper.pdf' to server
Associated artifact paper (242[7](https://github.com/openneuropet/PET2BIDS/actions/runs/5936971364/job/16098466945#step:5:8)614[9](https://github.com/openneuropet/PET2BIDS/actions/runs/5936971364/job/16098466945#step:5:10)) with run #2245
```

It's on the server? Which is something that I say sarcastically, I hope the authors of the plugin/action aren't similarly inclined. I'll dig around.


> also note sure where codemeta.json should seat? in paper? or just root (seems more logical -- can't find the JOSS link about that)

If it's only relevant to the code used to generate the paper then I think it should stay there, if it has other uses then maybe it should go top level? This already seems like black magic, so tread carefully.

**Comment by bendhouseart** [comment]
Posting here for reference:

Per the [documentation](https://github.com/openjournals/openjournals-draft-action) it should have committed it to the repo, but if it failed then it should have told us.

**Comment by bendhouseart** [comment]
Oh cool, it's here?

<img width="2518" alt="Screenshot 2023-08-24 at 1 21 48 PM" src="https://github.com/openneuropet/PET2BIDS/assets/28850131/5579e419-fced-4489-bc2f-7184edf9a94b">

Looks like it's stamped with draft though, almost there.

**Comment by CPernet** [comment]
?? yes it builds but `Uploaded '206252' bytes from '/home/runner/work/PET2BIDS/PET2BIDS/paper.pdf' to server` which server? I cannot see the pdf anywhere - I must be dumber than I thought, lol

**Comment by bendhouseart** [comment]
Well, I'm as lost as you. There's no `non-draft` option or action that I can locate.

Perhaps it's time to page the last contributors to the action we're using -> @M-Colley and @tarleb

**Comment by M-Colley** [comment]
Hey @bendhouseart, if you go to Summary and then under artifacts, you can download the pdf :) 

https://github.com/openneuropet/PET2BIDS/actions/runs/5936971364

**Comment by CPernet** [comment]
OMG I'm blind, thx
