### ISSUE TITLE
Bring Heuristic Python Methods up to Parity with Matlab 

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/PET2BIDS#97]
Breaking out these last two issues from a previous pull request to reduce size of PR:

- [x] ConvolutionKernel see -> [159](https://github.com/openneuropet/PET2BIDS/blob/83ced8ed7106f2ca2084fae462c5f4c947c28c8e/matlab/updatejsonpetfile.m#L159)
- [x] dicom nucleotides see -> [184](https://github.com/openneuropet/PET2BIDS/blob/83ced8ed7106f2ca2084fae462c5f4c947c28c8e/matlab/updatejsonpetfile.m#L184)

Need to add the above two functions/heuristics to python code.

**Comment by CPernet** [comment]
solve recon method using https://github.com/openneuropet/PET2BIDS/blob/main/matlab/get_recon_method.m

**Comment by bendhouseart** [comment]
Closed nucleotides wit pull request #111
