### ISSUE TITLE
BUG: Mandatory BIDS fields not appearing post conversion

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/PET2BIDS#99]
**Describe the bug**
Mandatory BIDS fields not populating in sidecar json, should populate with null or empty values in the event they aren't collected from metadata file or from dicom fields.

**To Reproduce**
Run dcm2niix4pet on a folder full of dicoms
```
dcm2niix4pet folder_full_of_pet_dicoms
```

**Expected behaviour**
Empty required PET bids fields should be present in the JSON if they're not collected from dcm2niix, the PET dicom headers, metadata spreadsheets or lastly from additional command line arguments. 

**Desktop (please complete the following information):**
 - OS: linux
 - Version python 0.0.8

**Comment by CPernet** [comment]
i don't think it should populate with null - users may want to use for there own purpose, the matlab code simply returns warnings ; see https://github.com/openneuropet/PET2BIDS/blob/main/matlab/updatejsonpetfile.m#L73

**Comment by bendhouseart** [comment]
You've sold me on on this; sticking with warnings and closing this issue.
